### PR TITLE
Fix issue with remote hash

### PR DESCRIPTION
**Pull request by GreatOldOne**
Hash buffered cheat.php from GitHub.

### CODE REVIEW

**Comment by xPaw** [comment]
This will most likely have the same problem with new lines.

**Comment by GreatOldOne** [comment]
Nah, I just tested.
Got 91b8af460c974e26ef01fa4ba8c1922ff4d7be91 from remote and Python.

**Comment by GreatOldOne** [comment]
I think it returns the hash for the blob. Tested it against their base64 content, but also got the wrong hash.

**Comment by xPaw** [comment]
Can you rebase this PR?

**Comment by GreatOldOne** [comment]
Yeah, I'll also fix the return value to be == to local if it fails, to prevent it displaying a message.

**Pull request closed without merging**
