### PR TITLE
Token Parameterization

### PR DESCRIPTION
**Pull request by SubstituteCS**
Allows for passing either a file with the token, or the token directly to the script.

### CODE REVIEW

**Comment by Scrxtchy** [comment]
825c24eb57a682b37ba89042ff57fafb00649b13

**Comment by SubstituteCS** [comment]
Yes, I understand that, I added the option of passing the filename of a token instead of a token directly.  This is mostly the same as the closed PR I submitted that did that, except this one also allows for a token directly instead of a file because xPaw wants that. @Scrxtchy

**Comment by Scrxtchy** [comment]
`<+xPaw> why even bother providing a file name if you're going to give it a param`

**Comment by SubstituteCS** [comment]
As stated before, I run the bot for members of different Discords, all of which I need to keep organized for when they want me to stop the bot so they, themselves can play the game.
Tokens do not make this easy, files with their names that have the contents of their tokens do.

**Comment by xPaw** [comment]
I already said you can pipe file contents into the script.

`php cheat.php "$(< file.txt)"`. Can you not do that?

**Comment by SubstituteCS** [comment]
While that is possible, most users wouldn't know about piping file contents.
Tons of people are having a hard enough time just setting up PHP. 🤷

**Comment by xPaw** [comment]
Most people won't be running multiple accounts. And providing token directly in argument is still much easier than trying to manage multiple files.

**Pull request closed without merging**
