### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ArtieMcD**

### CODE REVIEW

**Comment by DarkMio** [comment]
Aka use the linux manual.

**Comment by ArtieMcD** [comment]
The linux manual is kinda weak, and this is detailed steps to use the supported linux subsystem on Windows 10.

**Comment by xPaw** [comment]
Just use cheat.bat on Windows.

**Comment by ArtieMcD** [comment]
That's the point, cheat.bat is requiring the install of php, when windows 10 ALREADY supports PHP via it's windows services for linux.       This is a MUCH more efficient way to run php scripts on Windows 10.

**Comment by DarkMio** [comment]
With efficient you mean installing an entire OS on your OS.

**Comment by ArtieMcD** [comment]
No of course not. That's not how WSL works.

**Comment by DarkMio** [comment]
Tell me how you're not installing a Linux Kernel.

**Comment by ArtieMcD** [comment]
How about I give you the Microsoft reference that explains it.       Windows 10 WSL emulates the linux kernel and translates the system calls to the NT API.   Each WSL instance you run (and you can run as many as you want) are running linux kernel at all. 

https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/

**Pull request closed without merging**
