### PR TITLE
Make Contributing guidelines

### PR DESCRIPTION
**Pull request by ALEEF02**

### CODE REVIEW

**Comment by PsyBooty** [comment]
Hey guys ther is no issue but i think is a valid point ther is atributs on itens now!

**Comment by JourneyOver** [comment]
How many people you actually expect to read this xD

**Comment by ALEEF02** [comment]
¯\_(ツ)_/¯

**Comment by ALEEF02** [comment]
No reason _not_ to add it @duttaditya18

**Comment by xPaw** [comment]
I think with issues closed this isn't necessary.

**Pull request closed without merging**
