### PR TITLE
add docker-compose file

### PR DESCRIPTION
**Pull request by n1trux**
Pretty much self-explanatory.

Should I add instructions in the README?

### CODE REVIEW

**Comment by joandrsn** [comment]
You disclosed your token publicly. Your token should be treated as a password.

**Comment by Darksider3** [comment]
@joandrsn Not entirely sure, but isn't that token JUST for salien, what means that you can't do anything malicious with it except spamming the server?

**Comment by n1trux** [comment]
>You disclosed your token publicly. Your token should be treated as a password.

[NO I DID NOT](https://www.youtube.com/watch?v=Jv3MhjSmR3c)

`md5sum downloadphp.ps1`

joke's on you, m8

**Comment by xPaw** [comment]
Closing as repository will be archived.

**Pull request closed without merging**
