### PR TITLE
better wording for heroku manual

### PR DESCRIPTION
**Pull request by VladTheImpaller**

### CODE REVIEW

**Comment by JourneyOver** [comment]
This PR is not needed thanks to PR #190 once it gets merged. Just saying

**Comment by ALEEF02** [comment]
@VladTheImpaller Close the PR?

**Comment by VladTheImpaller** [comment]
Yes that's cool. @ALEEF02

**Comment by JourneyOver** [comment]
No he is telling you to close it @VladTheImpaller xD click the close button down below.

**Pull request closed without merging**
