### PR TITLE
Countdown timer while in a zone

### PR DESCRIPTION
**Pull request by nsilvestri**
Added a quick little countdown timer to show how much time is left in the zone.

Sorry if something is wrong, I've never done a open source PR and haven't used PHP before.

### CODE REVIEW

**Comment by xPaw** [comment]
Unnecessarily spammy.

**Comment by nsilvestri** [comment]
I can see how 110 extra lines would be spammy if it was redirected to an output file, but since most people aren't doing that, it's only one extra line to stdout on the command line. May I ask why you thought this was spammy?

**Comment by xPaw** [comment]
Yeah sorry I missed the `\r`.

There's still an issue with this approach though that it somewhat blocks scrolling up in the output because it refreshes every second.

**Comment by nsilvestri** [comment]
Ah, good point, I didn't even notice that was happening. Thank you for the feedback, I appreciate it a lot.

**Comment by DerakDerantick** [comment]
Why couldn't you set it to the titlebar of the window? Avoid spamming the main thing.

**Comment by nsilvestri** [comment]
@DerakDerantick that change is shell dependent and wouldn't work across all systems.

**Pull request closed without merging**
