### PR TITLE
Make sleep after E10: 10 seconds

### PR DESCRIPTION
**Pull request by ALEEF02**
3 seconds is too fast fills up log quickly

### CODE REVIEW

**Comment by rossengeorgiev** [comment]
Make sleep after closing PR

**Comment by ALEEF02** [comment]
What?

**Comment by rossengeorgiev** [comment]
sleep too long

**Comment by ALEEF02** [comment]
Made it 7 seconds

**Comment by rossengeorgiev** [comment]
no too long

**Pull request closed without merging**
