### PR TITLE
Fix xpaw's horrible formatting

### PR DESCRIPTION
**Pull request by rannmann**

### CODE REVIEW

**Comment by Byter09** [comment]
You could've searched in closed PRs. I already submitted a PR regarding PSR-2. It was closed in minutes... :P

**Comment by Marco01809** [comment]
While I agree that the code style is atrocious, making a PR just replacing the lead developers' preferred style might be somewhat arrogant.

**Comment by Byter09** [comment]
@Marco01809
I agree for such a project. But PSR-2 is simply a standard and basically every IDE has a feature to automatically format this way. So that's no excuse :)

**Comment by JourneyOver** [comment]
> But PSR-2 is simply a standard and basically every IDE has a feature to automatically format this way

Doesn't mean that people have to follow that standard if they don't want to. Believe it or not people are free to follow or not follow whatever standard they want.

**Comment by NoXPhasma** [comment]
The maintainer of a project has the right to chose the coding style. If you don't like to provide code this way, you are free to get along.

If you wanted to start a discussion about a change of the code style, you started it the complete wrong way.

**Comment by Scrxtchy** [comment]
image
image

**Comment by mat8913** [comment]
Who cares? It's not like anyone's gonna look at this after the event ends.

Besides, if xpaw wanted good looking code, he wouldn't have made it in php.

**Pull request closed without merging**
