### PR TITLE
Env variable to disable colors

### PR DESCRIPTION
**Pull request by GreatOldOne**
https://github.com/SteamDatabase/SalienCheat/issues/189

### CODE REVIEW

**Comment by JourneyOver** [comment]
Hmm something is wrong, whenever I add `DISABLE_COLORS_SALIENS` to the end of the my call I just run into `Failed to find your token. Verify token.txt`

This is the call `php cheat.php MYTOKEN DISABLE_COLORS_SALIENS`

**Comment by GreatOldOne** [comment]
export DISABLE_COLORS_SALIENS=true

or

export DISABLE_COLORS_SALIENS=1

**Comment by Alamei** [comment]
Right now, the "Welcome to..." on line 61 has some hardcoded ANSI colors. You may want to strip those based on the environment variable as well, for consistency.

**Comment by JourneyOver** [comment]
I got it figured it now thanks to @Alamei :D going to rebase my PR and fix up my PR now to accomplish what I was wanting to do thanks to this PR

**Comment by PalmtopTiger** [comment]
Please check the actual color support instead of/in addition to enviroment variable.
https://github.com/SteamDatabase/SalienCheat/issues/189#issuecomment-400521245

**Comment by PalmtopTiger** [comment]
We also should follow the script style, so I suggest to rename the variable to DISABLE_COLORS.

**Comment by PalmtopTiger** [comment]
Because of this, there is `function_exists` before each call.

**Comment by GreatOldOne** [comment]
sapi_windows_vt100_support($output)

This will fail even if you've a vt100 enabled terminal if you are not using PHP 7+.

**Comment by PalmtopTiger** [comment]
If you use Cmder/ConEmu, the ANSICON and ConEmuANSI variables are defined.
If you use Windows 10 and PHP 5, so... this is weird because PHP 7.2 is installed by the PowerShell script.

**Comment by PalmtopTiger** [comment]
If you use PHP5 on Win10 you installed it manually, so probably you are a power user. And if you didn't use Cmder you can still define one of the above variables.
There are many screenshots on the Reddit of cmd with broken color codes. I believe that we should pay more attention to inexperienced users.

**Comment by JourneyOver** [comment]
As long as whatever gets done work with heroku then I will be happy, so that people can stop complaining about the logs on heroku being messy.

**Comment by GreatOldOne** [comment]
Added color support check with the ability to override the result with env variables.

**Comment by JourneyOver** [comment]
new variable name @GreatOldOne ?

**Comment by GreatOldOne** [comment]
Try it without the variable and see if it works with the color support check.

**Comment by JourneyOver** [comment]
I'm asking so I can change the variable name in #190 to match the variable name you have set.

**Comment by GreatOldOne** [comment]
Yes, it's FORCE_DISABLE_COLORS.

**Comment by JourneyOver** [comment]
Okay thank you

**Comment by PalmtopTiger** [comment]
@JourneyOver, `FORCE_COLORS_SETTING=0`.
And just `FORCE_COLORS` will be better :D

**Pull request closed without merging**
