### PR TITLE
Updated README.md for DAU cases

### PR DESCRIPTION
**Pull request by M4n1us**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Wouldn't assume the end user is running Windows

**Comment by Faalagorn** [comment]
While I agree, it already assumes so by stating to download Windows' PHP binary and extract it to C:/php

**Comment by SuperSandro2000** [comment]
7. and 4. do not sound great at all

**Comment by xPaw** [comment]
I added a link to reddit thread in readme

**Pull request closed without merging**
