### PR TITLE
Linux (sh) runner/updater

### PR DESCRIPTION
**Pull request by SavageCore**
Created a script in sh that uses `screen` to run multiple instances of the script as defined in `tokens.txt`. Will check for updates via git.

### CODE REVIEW

**Comment by xPaw** [comment]
No updaters.

**Comment by Martan404** [comment]
The reason for this as I understand is because it's a security issue. Malicious could be injected and spread to everyone running the script, without the users knowledge. Hence why the developers deny auto updaters. It's up to every user to check the code before running it. Nothing stops you from doing it yourself tho.

**Comment by SavageCore** [comment]
Well that's true for the vast majority of code published on GitHub, we inherently trust repos as only maintainers can commit to master etc.

**Comment by Sanaki** [comment]
Unfortunately this topic has come up in the past with regards to steam sale minigames, and the number of headaches it has caused simply isn't worthwhile.

**Pull request closed without merging**
