### PR TITLE
don't clear $AccountID if it has been set already

### PR DESCRIPTION
**Pull request by hintswen**

### CODE REVIEW

**Comment by xPaw** [comment]
Doesn't it make sense for argument to override env?

**Comment by dusekdan** [comment]
Also, nested ternary operator. :'(

**Comment by mat8913** [comment]
Maybe this?

    if( $argc > 2 )
    {
    	$AccountID = $argv[ 2 ];
    }
    if( $argc > 1 )
    {
    	$Token = $argv[ 1 ];
    }

**Comment by xPaw** [comment]
It makes sense for CLI arguments to override ones provided in ENV.

**Comment by mat8913** [comment]
I think you misunderstand. The problem is that if you only specify the "Token" CLI argument, the "AccountID" ENV is ignored.

Eg.

    ACCOUNTID=123456789 ./cheat.php adc83b19e793491b1c6ea0fd8b46cd9f32e592fc

**Comment by xPaw** [comment]
Ah sorry, will fix.

**Pull request closed without merging**
